# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NalleBerg.IPGui
PackageVersion: 4.1.9
InstallerType: msi
ProductCode: '{4442AFA4-18F8-46B3-975B-8F1A471A3F14}'
Installers:
- Architecture: x64
  InstallerUrl: https://prog.nalle.no/user/pages/01.home/apps/IPGui-4.1.9-Setup.msi
  InstallerSha256: AB1F959E5A5A6B290B4C4B4CD131121D09EDC5BB36E5B1A2B8453AA0C491572B
ManifestType: installer
ManifestVersion: 1.12.0
